### PR TITLE
feat: ts support and name change

### LINKED ISSUE #5: TS problem
```
  Try `npm i --save-dev @types/vue-command-palette` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-command-palette';`ts(7016)
  
  ```
  

- [x] TS support
- [x] Volar support

### PR DESCRIPTION
**Pull request by productdevbook**
close #5 

```vue
<template>
  <CommandDialog :visible="visible" theme="custom">
    <template #header>
      <CommandInput placeholder="Type a command or search..." />
    </template>
    <template #body>
      <CommandList>
        <CommandEmpty>No results found.</CommandEmpty>

        <CommandGroup heading="Letters">
          <CommandItem>a</CommandItem>
          <CommandItem>b</CommandItem>
          <CommandSeparator />
          <CommandItem>c</CommandItem>
        </CommandGroup>

        <CommandItem>Apple</CommandItem>
      </CommandList>
    </template>
  </CommandDialog>
</template>

```

new name change `.` delete

and volar support auto

image

### CODE REVIEW

**Comment by xiaoluoboding** [comment]
Hey @productdevbook

Thank you for resolving the TS problem, awesome work.

Is there a way to write it that solves the TS problem while using [Namespaced Components](https://vuejs.org/api/sfc-script-setup.html#namespaced-components)?

My original idea was to use [Namespaced Components](https://vuejs.org/api/sfc-script-setup.html#namespaced-components) to implement it.

**Comment by productdevbook** [comment]
I'm taking a look now, maybe

**Comment by productdevbook** [comment]
No, this does not seem possible, there is no point in forcing the structure.

It is better to proceed this way.

**Comment by RomainLanz** [comment]
Hey, both of you 👋🏻 

Is there any way I can help to have this PR merged and released?

**Comment by xiaoluoboding** [comment]
PRs welcome

**Comment by RomainLanz** [comment]
I mean, is there any change needed in this PR?

**Comment by productdevbook** [comment]
no, it just needs to accept the structure

**Comment by BayBreezy** [comment]
Question.. is this a thing? Seeing that it was closed and something got deleted...
Some TS help in Volar with this would be nice

**Pull request closed without merging**
